# -*- coding: utf-8 -*-
"""retail-peak-hours-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uEGPJ4kODfNI_-dJsyFzC00h8bRo4UG
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Online_Retail.csv', encoding='latin-1')

df.head(5)

df.info()

"""По первоначальному анализу данных можно понять, что столбец 'InvoiceDate' имеет тип данных object. Работать с таким типом данных будет неудобно, поэтому сразу проведет преобразование к другому типу данных"""

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], format='%m/%d/%y %H:%M')

"""Добавим новый столбец 'Revenue', который будет показывать выручку с каждого заказа"""

df['Revenue'] = df['Quantity'] * df['UnitPrice']

"""В рамках исследования будем исследовать пиковые часы. Для этого создадим новый столбец, который будет содержать час, в который совершена покупка"""

df['Hour'] = df['InvoiceDate'].dt.hour

"""Рассчитаем общую выручку за каждый час"""

hourly_revenue = df.groupby('Hour')['Revenue'].sum().sort_values(ascending=False).reset_index()
hourly_revenue

"""Период времени с 10:00 по 15:00 оказался самым прибыльным. Каждый час из этого промежутка принес более 1 млн единиц валюты (к сожалению, в датасете не указано какая именно валюта используется). Самыми не прибыльными часами оказались 6:00 и 20:00. В 6:00 мы получили отрицательное значение выручки, соответственно, можно сделать вывод о том, что были возвраты

Также предлагается найти самый прибыльный час (пиковый)
"""

best_hour_revenue = hourly_revenue.idxmax()
best_hour_revenue

"""В 12:00 выручка является максимальной. Следовательно 12:00 является пиковым часом по выручке

Посчитаем количество заказов за каждый час
"""

hourly_orders = df.groupby('Hour')['InvoiceNo'].nunique().sort_values(ascending=False).reset_index()
hourly_orders

"""Полученные данные коррелирует с теми, что мы получили при подсчете выручку. Период времени с 10:00 по 15:00 показал наибольшее число заказов. В каждый час из этого промежутка совершалось более 3000 заказов (В 10:00 было совершено 2961 заказов, но округлим). Часами с наименьшим числом заказов являются 6:00 и 20:00, поэтому почасовая выручка наименьшая

Также предлагается найти самый активный час (пиковый)
"""

best_hour_orders = hourly_orders.idxmax()
best_hour_orders

"""12:00 является самым активным (пиковым) часом

Визуализация
"""

sns.lineplot(data=hourly_revenue, x='Hour', y='Revenue')
plt.grid(alpha=0.3)
plt.xlabel('Часы')
plt.ylabel('Суммарная выручка')
plt.title('Выручка в зависимости от времени суток')
plt.show()

sns.lineplot(data=hourly_orders, x='Hour', y='InvoiceNo')
plt.grid(alpha=0.3)
plt.xlabel('Часы')
plt.ylabel('Общее количество заказов')
plt.title('Активность в зависимости от времени суток')
plt.show()

fig, ax1 = plt.subplots(figsize=(12,6))

sns.lineplot(data=hourly_revenue, x='Hour', y='Revenue', ax=ax1, color='blue')
ax1.set_xlabel('Часы')
ax1.set_ylabel('Суммарная выручка', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')
ax1.grid(alpha=0.3)


ax2 = ax1.twinx()
sns.lineplot(data=hourly_orders, x='Hour', y='InvoiceNo', ax=ax2, color='red')
ax2.set_ylabel('Общее количество заказов', color='red')
ax2.tick_params(axis='y', labelcolor='red')
ax2.grid(alpha=0.3)

plt.title('Активность в зависимости от времени суток')
plt.show()

"""Проведенный анализ почасовой активности интернет-магазина показал, что пик выручки и наибольшее количество заказов приходятся на 12:00, при этом период с 10:00 до 15:00 является самым прибыльным и активно приносит более миллиона единиц валюты за каждый час. Наименьшая активность наблюдается в 6:00 и 20:00, причем в 6:00 зафиксирована отрицательная выручка, что может указывать на возвраты товаров в это время. Таким образом, основная масса покупок совершается клиентами в рабочее время, вероятно, в обеденный перерыв, что позволяет рекомендовать усиление маркетинговой активности в промежутке с 10:00 до 15:00 для максимизации прибыли, а также проведение дополнительного анализа причин возвратов в ранние утренние часы."""